### ISSUE TITLE
[BUG] : Relic -> Ecu restoration removes all districts

### ISSUE THREAD

**Issue by weirfish** [Stellaris-Immortal/retile#3]
Both decision districts and normal districts are removed, and the removal of these jobs force-demolishes any related buildings. This then causes pops to migrate away, as they no longer have housing or jobs.

**Comment by weirfish** [comment]
This was specifically observed on the Rubricator relic world, but may apply to any; I haven't had the opportunity to test it yet, for want of keeping my current run going without console commands or having to war neighbours to get other relic worlds.

**Comment by gebnar** [comment]
I'm surprised the regular districts also get deleted. I wrote a whole script just to fix them up properly. Maybe I only put it on the regular ecu decision. We'll be putting out a hotfix later today that should fix this issue.

**Comment by weirfish** [comment]
It might be because the relic ecu science district is different? As I remember it, at least. I won't be able to double check what's going on with it until later today when I get back to my home computer.

**Comment by gebnar** [comment]
That's true, though the have conversion code. I'll get it figured out and tested today.

**Comment by gebnar** [comment]
Fixed completely - tested and verified.

Also, relic worlds now count digsite districts toward the required number of city districts for conversion.

All special districts should be preserved.

**Comment by ziyakaz** [comment]
I'm finding I'm still having this issue:
![image](https://user-images.githubusercontent.com/57647601/68776922-761e1c80-05f6-11ea-9db7-23ce3e361a0a.png)

Should I start a new game (this one was started before the hotfix)?

**Comment by gebnar** [comment]
@ziyakaz I don't think starting a new game would make any difference. Are you running *ANY* mods alongside SI? And if so what are they? Because I tested the fix several times, and got perfect results on every world.
It's also possible that somehow the changes didn't make it into the hotfix, though I thought they did. I'll try loading the steam workshop version of the mod, and see what I find.

**Comment by ziyakaz** [comment]
I can't recreate this issue myself after trying a couple more times (once with only this mod loaded, once with all mods loaded). It's possible Steam didn't pick up the update for the hotfix.

Mods are (in this order):
- Beautiful Universe v2.0
- Stellaris Performance Mod - Galaxy Dust Tweak
- Flags in the void
- LLX's Mods - A Lot of Dimorphism (2.3 'Wolfe')
- Cybrxkhan's Assortment of Namelists for Stellaris
- UI Overhaul Dynamic
- UI Overhaul Dynamic - Checksum Schism Version
- UI Overhaul Dynamic + Complete Colors
- UI Bigger Font
- SpeedDial
- UI Overhaul Dynamic + SpeedDial
- Tiny Outliner v2
- Tiny Fleets
- UI Overhaul Dynamic + Tiny Outliner v2
- Start with AutoExplore
- Ziaskehorn: an Ancient Relics Story
- Intervene: Help Friendly Nations
- What's The Rush?
- Downscaled Ships
- Researcher Trait 'Fix'
- Close Precursors
- Stellaris Immortal (alpha)

**Comment by gebnar** [comment]
What is that researcher trait fix?

**Comment by gebnar** [comment]
Gonna close this for now. Please reopen if it happens again!
